
doctor-configuration:
  specializations:
    - surgeon
    - therapeut

clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

spring:
  jackson.property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create

  datasource:
    username: postgres
    password: 1
    url: jdbc:postgresql:pet_clinic

logging.level.org.hibernate: DEBUG