
doctor-configuration:
  specializations:
    - surgeon
    - doctor

clinic-info:
  name: 'my clinic'
  working-hours: '8-17'

spring:
  jackson.property-naming-strategy: SNAKE_CASE
  jpa.show-sql: true

logging.level.org.hibernate: DEBUG